import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safe: { flex: 1, backgroundColor: "#fff" },
	flex: { flex: 1 },
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 12,
		paddingVertical: 10,
		borderBottomWidth: 1,
		borderBottomColor: "#eee",
	},
	backBtn: { width: 36, height: 36, justifyContent: "center", alignItems: "center" },
	headerTitle: {
		flex: 1,
		textAlign: "center",
		fontSize: 16,
		fontWeight: "700",
		color: "#111",
	},
	centerBox: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		padding: 24,
		gap: 12,
	},
	muted: { color: "#777", fontSize: 14, textAlign: "center" },
	errorText: { color: "#c0392b", fontSize: 15, textAlign: "center" },
	retryBtn: {
		marginTop: 8,
		backgroundColor: "#22a45d",
		paddingHorizontal: 20,
		paddingVertical: 10,
		borderRadius: 8,
	},
	retryText: { color: "#fff", fontWeight: "700" },
	mapWrap: { flex: 1, position: "relative" },
	map: { flex: 1 },
	noLocOverlay: {
		position: "absolute",
		top: 12,
		left: 12,
		right: 12,
		backgroundColor: "rgba(17,17,17,0.8)",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		paddingVertical: 10,
		borderRadius: 10,
	},
	noLocText: { color: "#fff", fontWeight: "600" },
	sourceBadge: {
		position: "absolute",
		top: 12,
		left: 12,
		flexDirection: "row",
		alignItems: "center",
		gap: 7,
		backgroundColor: "rgba(17,17,17,0.82)",
		paddingVertical: 7,
		paddingHorizontal: 12,
		borderRadius: 20,
	},
	sourceDot: {
		width: 9,
		height: 9,
		borderRadius: 5,
		backgroundColor: "#f1c40f",
	},
	sourceDotLive: { backgroundColor: "#22a45d" },
	sourceBadgeText: { color: "#fff", fontWeight: "600", fontSize: 12 },
	card: {
		backgroundColor: "#fff",
		paddingHorizontal: 16,
		paddingTop: 14,
		paddingBottom: 16,
		borderTopWidth: 1,
		borderTopColor: "#eee",
		gap: 12,
	},
	riderRow: { flexDirection: "row", alignItems: "center", gap: 12 },
	avatar: {
		width: 42,
		height: 42,
		borderRadius: 21,
		backgroundColor: "#22a45d",
		justifyContent: "center",
		alignItems: "center",
	},
	riderName: { fontSize: 16, fontWeight: "700", color: "#111" },
	callBtn: {
		width: 42,
		height: 42,
		borderRadius: 21,
		backgroundColor: "#2d8cff",
		justifyContent: "center",
		alignItems: "center",
	},
	updatedText: { color: "#999", fontSize: 12 },
	mapsBtn: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		backgroundColor: "#22a45d",
		paddingVertical: 13,
		borderRadius: 10,
	},
	mapsBtnDisabled: { backgroundColor: "#cccccc" },
	mapsBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
});
