import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  topNav: {
    height: 80,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 0,
    backgroundColor: "#fff",
    zIndex: 100,
    marginTop: 30,
  },
  logo: {
    width: 60,
    height: 60,
  },
  searchWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 42,
    marginLeft: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#fff",
    paddingRight: 5,
  },
  searchBox: {
    flex: 1,
    height: "100%",
    paddingHorizontal: 12,
    fontSize: 13,
    color: "#000",
  },
  locationContainer: {
    position: "relative",
    marginLeft: 2,
    flexShrink: 0,
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 2,
    paddingVertical: 6,
    maxWidth: 70,
  },
  locationText: {
    color: "#000",
    fontSize: 11,
    fontWeight: "600",
    marginLeft: 2,
    maxWidth: 40,
  },
  // --- City picker modal -----------------------------------------------
  // Rendered in a Modal (not as an absolute child of the fixed-height header)
  // so the long city list can actually scroll instead of being clipped.
  cityModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
  },
  cityModalSheet: {
    width: "100%",
    maxWidth: 360,
    maxHeight: "70%",
    backgroundColor: "#fff",
    borderRadius: 14,
    paddingTop: 14,
    paddingBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  cityModalTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#000",
    textAlign: "center",
    marginBottom: 10,
  },
  citySearchInput: {
    height: 40,
    marginHorizontal: 12,
    marginBottom: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    fontSize: 14,
    color: "#000",
  },
  cityModalList: {
    flexGrow: 0,
  },
  dropdownTextActive: {
    color: "#f4bb26",
    fontWeight: "700",
  },
  dropdownContainer: {
    position: "relative",
    marginLeft: 2,
    marginRight: 8,
    flexShrink: 0,
  },
  dropdownButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingVertical: 6,
  },
  flag: {
    width: 20,
    height: 14,
    borderRadius: 3,
    marginRight: 3,
  },
  dropdownText: {
    color: "#000",
    fontSize: 14,
  },
  arrow: {
    marginLeft: 2,
    fontSize: 11,
    color: "#333",
  },
  dropdownList: {
    position: "absolute",
    top: 45,
    right: 0,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    width: 130,
    zIndex: 200,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  rowReverse: {
    flexDirection: "row-reverse",
  },
  marginRightSmall: {
    marginLeft: 0,
    marginRight: 2,
  },
});
