import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  topNav: {
    height: 80,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 10,
    paddingRight: 0,
    backgroundColor: "#fff",
    zIndex: 100,
    marginTop: 30,
  },
  logo: {
    width: 60,
    height: 60,
  },
  searchWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    height: 42,
    marginLeft: 10,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#ccc",
    backgroundColor: "#fff",
    paddingRight: 5,
  },
  searchBox: {
    flex: 1,
    height: "100%",
    paddingHorizontal: 12,
    fontSize: 13,
    color: "#000",
  },
  locationContainer: {
    position: "relative",
    marginLeft: 2,
    flexShrink: 0,
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 2,
    paddingVertical: 6,
    maxWidth: 70,
  },
  locationText: {
    color: "#000",
    fontSize: 11,
    fontWeight: "600",
    marginLeft: 2,
    maxWidth: 40,
  },
  cityDropdownList: {
    position: "absolute",
    top: 40,
    right: 0,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    width: 170,
    maxHeight: 260,
    zIndex: 300,
  },
  dropdownTextActive: {
    color: "#f4bb26",
    fontWeight: "700",
  },
  dropdownContainer: {
    position: "relative",
    marginLeft: 2,
    marginRight: 8,
    flexShrink: 0,
  },
  dropdownButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 0,
    paddingVertical: 6,
  },
  flag: {
    width: 20,
    height: 14,
    borderRadius: 3,
    marginRight: 3,
  },
  dropdownText: {
    color: "#000",
    fontSize: 14,
  },
  arrow: {
    marginLeft: 2,
    fontSize: 11,
    color: "#333",
  },
  dropdownList: {
    position: "absolute",
    top: 45,
    right: 0,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    width: 130,
    zIndex: 200,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  rowReverse: {
    flexDirection: "row-reverse",
  },
  marginRightSmall: {
    marginLeft: 0,
    marginRight: 2,
  },
});
