import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	screen: { flex: 1, backgroundColor: "#FFFFFF" },
	scrollContent: { paddingBottom: 50 },
	topBanner: {
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#f4bb26",
		borderBottomLeftRadius: 60,
		borderBottomRightRadius: 60,
		overflow: "hidden",
	},
	bottomInputsContainer: { paddingHorizontal: 24, marginTop: 20 },
	inputBoxWrapper: {
		marginBottom: 12,
		width: "100%",
		minHeight: 55,
		borderWidth: 1,
		borderColor: "#d1d5db",
		borderRadius: 12,
		justifyContent: "center",
	},
	inputBoxText: { padding: 15 },
	phoneRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 12,
		width: "100%",
		minHeight: 55,
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 12,
		paddingHorizontal: 12,
	},
	countryCodeText: { fontSize: 16, fontWeight: "600", marginRight: 8 },
	phoneDivider: { width: 1, height: 24, backgroundColor: "#e0e0e0", marginRight: 10 },
	phoneInput: { flex: 1, paddingVertical: 15, fontSize: 16 },
	passwordRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 12,
		width: "100%",
		borderWidth: 1,
		borderColor: "#000000",
		borderRadius: 12,
	},
	passwordInput: { flex: 1, padding: 15 },
	eyeButton: { paddingHorizontal: 10 },
	cityPicker: { marginBottom: 6, backgroundColor: "#f2f2f2", minHeight: 55 },
	locationButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		alignSelf: "stretch",
		marginBottom: 14,
		paddingVertical: 10,
		paddingHorizontal: 12,
		borderRadius: 10,
	},
	locationButtonText: { fontSize: 14, fontWeight: "600", lineHeight: 19, flex: 1, flexWrap: "wrap" },
	mapPinButton: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		alignSelf: "stretch",
		marginBottom: 14,
		paddingVertical: 10,
		paddingHorizontal: 12,
		borderRadius: 10,
	},
	mapPinButtonText: { fontSize: 14, fontWeight: "600", lineHeight: 19, textDecorationLine: "underline", flex: 1, flexWrap: "wrap" },
	syncingContainer: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginBottom: 10,
		paddingVertical: 8,
		paddingHorizontal: 12,
		borderRadius: 10,
		backgroundColor: "#fff8e6",
	},
	syncingText: { color: "#7a6a2e", fontSize: 13, fontWeight: "600", lineHeight: 18, flex: 1, flexWrap: "wrap" },
	googleButton: {
		flexDirection: "row",
		backgroundColor: "#ffffff",
		borderRadius: 15,
		paddingVertical: 13,
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		marginTop: 12,
		borderWidth: 1,
		borderColor: "#d1d5db",
	},
	googleButtonText: { color: "#000", fontWeight: "700", fontSize: 16 },
	appleButton: {
		flexDirection: "row",
		backgroundColor: "#000000",
		borderRadius: 15,
		paddingVertical: 13,
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
		marginTop: 12,
	},
	appleButtonText: { color: "#fff", fontWeight: "700", fontSize: 16 },
	logoVideo: {
		width: 200,
		height: 200,
	},
	registerButton: {
		backgroundColor: "#f4bb26",
		borderRadius: 15,
		paddingVertical: 15,
		width: "100%",
		alignItems: "center",
		marginBottom: 12,
	},
	registerButtonText: {
		color: "#fff",
		fontWeight: "bold",
		fontSize: 18,
	},
	loginPromptContainer: {
		alignItems: "center",
		marginTop: 10,
		marginBottom: 200,
	},
	loginPromptText: {
		color: "#000",
		fontSize: 18,
		fontWeight: "700",
	},
	loginPromptLink: {
		color: "#f4bb26",
		fontWeight: "700",
	},
	topNav: {
		height: 80,
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 10,
		backgroundColor: "#fff",
		zIndex: 100,
		marginTop: 30,
	},
	logo: {
		width: 60,
		height: 60,
	},
	searchBox: {
		flex: 1,
		height: 50,
		marginLeft: 10,
		borderRadius: 15,
		borderWidth: 1,
		borderColor: "#ccc",
		backgroundColor: "#fff",
		paddingHorizontal: 15,
		color: "#000",
	},
	dropdownContainer: {
		width: "100%",
		alignItems: "center",
		marginTop: 20,
		zIndex: 9999, // 🔥 FIX: ensures it appears above everything
	},

	dropdownButton: {
		flexDirection: "row",
		alignItems: "center",
		paddingHorizontal: 8,
		paddingVertical: 6,
	},

	dropdownList: {
		position: "absolute",
		top: 40,
		backgroundColor: "#fff",
		borderWidth: 1,
		borderColor: "#ccc",
		borderRadius: 10,
		shadowColor: "#000",
		shadowOpacity: 0.2,
		shadowRadius: 6,
		elevation: 10,
		width: 150,
		zIndex: 99999,
	},

	dropdownItem: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 12,
	},

	flag: {
		width: 24,
		height: 16,
		marginRight: 8,
		borderRadius: 3,
	},

	dropdownText: {
		color: "#000",
		fontSize: 14,
	},

	arrow: {
		marginLeft: 5,
		fontSize: 14,
		color: "#333",
	},
});
