import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
	safeArea: { flex: 1, backgroundColor: "#fff" },
	center: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "#fff",
	},
	backButton: {
		paddingHorizontal: 12,
		paddingTop: 12,
		paddingBottom: 4,
	},
	mainImageWrapper: {
		width: "100%",
		height: 220,
		backgroundColor: "#f7f7f7",
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
	},
	mainImage: { width: "100%", height: "100%" },
	mainPlaceholder: {
		fontSize: 64,
		fontWeight: "700",
		color: "#f4bb26",
	},
	title: {
		fontSize: 22,
		fontWeight: "700",
		color: "#222",
		textAlign: "center",
		marginTop: 12,
		paddingHorizontal: 16,
	},
	addAllBtn: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		backgroundColor: "#f4bb26",
		borderRadius: 10,
		paddingVertical: 14,
		marginHorizontal: 16,
		marginTop: 14,
	},
	addAllBtnDisabled: {
		backgroundColor: "#cccccc",
	},
	checkoutBtn: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		gap: 8,
		backgroundColor: "#22a45d",
		borderRadius: 10,
		paddingVertical: 14,
		marginHorizontal: 16,
		marginTop: 14,
	},
	addAllBtnText: {
		color: "#fff",
		fontWeight: "700",
		fontSize: 16,
	},
	sectionTitle: {
		fontSize: 18,
		fontWeight: "700",
		color: "#222",
		marginTop: 22,
		marginBottom: 8,
		paddingHorizontal: 16,
	},
	itemRow: {
		flexDirection: "row",
		alignItems: "center",
		paddingVertical: 10,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: "#f0f0f0",
	},
	itemImageWrapper: {
		width: 64,
		height: 64,
		borderRadius: 8,
		backgroundColor: "#f9f9f9",
		overflow: "hidden",
		justifyContent: "center",
		alignItems: "center",
	},
	itemImage: { width: "100%", height: "100%" },
	outOfStockOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: "rgba(0,0,0,0.45)",
		justifyContent: "center",
		alignItems: "center",
	},
	outOfStockText: {
		color: "#fff",
		fontWeight: "700",
		fontSize: 11,
	},
	itemInfo: {
		flex: 1,
		paddingHorizontal: 12,
	},
	itemName: {
		fontSize: 14,
		fontWeight: "600",
		color: "#222",
	},
	priceRow: {
		flexDirection: "row",
		alignItems: "center",
		gap: 8,
		marginTop: 4,
	},
	basePrice: {
		fontSize: 13,
		color: "#999",
		textDecorationLine: "line-through",
	},
	finalPrice: {
		fontSize: 15,
		fontWeight: "700",
		color: "#f4bb26",
	},
	qtyBox: {
		alignItems: "center",
		minWidth: 54,
	},
	qtyLabel: {
		fontSize: 11,
		color: "#888",
	},
	qtyValue: {
		fontSize: 16,
		fontWeight: "700",
		color: "#222",
	},
	emptyText: {
		fontSize: 14,
		color: "#777",
		textAlign: "center",
		marginTop: 20,
		paddingHorizontal: 16,
	},
	root: { flex: 1, backgroundColor: "#fff" },
	scrollContent: { paddingBottom: 120 },
});
